# Generated by Django 5.0.4 on 2024-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Electives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_elec",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                ("description_elec", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Электив",
                "verbose_name_plural": "Элективы",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=50, verbose_name="Направление"),
                ),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(max_length=50, verbose_name="Направление"),
                ),
            ],
            options={
                "verbose_name": "Профессия",
                "verbose_name_plural": "Профессии",
            },
        ),
    ]
