# Generated by Django 5.0.4 on 2024-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="job_id",
            field=models.IntegerField(default=1, verbose_name="job_id"),
            preserve_default=False,
        ),
    ]
